version: '3'

services:
  postgres-docker:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: smart-stock
    ports:
      - "5432:5432"

  adminer-docker:
    image: adminer
    restart: always
    ports:
      - 9000:8080
    depends_on:
      - postgres-docker